version: 2.1

executors:
  ruby-2_4_1:
    docker:
      - image: circleci/ruby:2.4.1
      - image: circleci/postgres:9.6.2-alpine
        name: postgres
  ruby-2_5_0:
    docker:
      - image: circleci/ruby:2.4.1
      - image: circleci/postgres:9.6.2-alpine
        name: postgres

jobs:
  lint:
    executor: ruby-2_4_1
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec standardrb

  build:
    parameters:
      ruby:
        type: executor
      rails:
        type: string
      postgres:
        type: string
    executor: << parameters.ruby >>
    steps:
      - checkout
      - run: RAILS_VERSION=<< parameters.rails >> PG_VERSION=<< parameters.postgres >> bundle install
      - run: RAILS_VERSION=<< parameters.rails >> PG_VERSION=<< parameters.postgres >> bundle exec rspec

workflows:
  version: 2
  test-ruby-builds:
    jobs:
      - lint
      - build:
          name: Rails v.<< matrix.rails >> Ruby << matrix.ruby >>
          matrix:
            parameters:
              ruby: ["ruby-2_4_1", "ruby-2_5_0"]
              rails: ["4.2.11.1", "5.1.6.2", "5.1.7", "5.2.3"] # "6.0.0"
              postgres: ["0.19.0", "0.21.0"]
          requires:
            - lint
