version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1

      - image: circleci/postgres:9.6.2-alpine
        name: postgres

    steps:
      - checkout

      - run: bundle install
      - run: bundle exec standardrb
      - run: rm Gemfile.lock

      - run: RUBY_VERSION=2.4.1 RAILS_VERSION=4.2.11.1 PG_VERSION=0.21.0 bundle install
      - run: RUBY_VERSION=2.4.1 RAILS_VERSION=4.2.11.1 PG_VERSION=0.21.0 bundle exec rspec
      - run: rm Gemfile.lock

      - run: RUBY_VERSION=2.4.1 RAILS_VERSION=5.1.7 PG_VERSION=0.21.0 bundle install
      - run: RUBY_VERSION=2.4.1 RAILS_VERSION=5.1.7 PG_VERSION=0.21.0 bundle exec rspec
      - run: rm Gemfile.lock

      - run: RUBY_VERSION=2.4.1 RAILS_VERSION=5.2.3 PG_VERSION=0.21.0 bundle install
      - run: RUBY_VERSION=2.4.1 RAILS_VERSION=5.2.3 PG_VERSION=0.21.0 bundle exec rspec
