version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1

      - image: circleci/postgres:9.6.2-alpine
        name: postgres
    parameters:
      ruby:
        type: string
      rails:
        type: string
      postgres:
        type: string
    steps:
      - checkout
      - run: bundle install
      - run: RUBY_VERSION=<< parameters.ruby >> RAILS_VERSION=<< parameters.rails >> PG_VERSION=<< parameters.postgres >> bundle install
      - run: RUBY_VERSION=<< parameters.ruby >> RAILS_VERSION=<< parameters.rails >> PG_VERSION=<< parameters.postgres >> bundle exec rspec
      - run: rm Gemfile.lock

workflows:
  version: 2.1
  test-ruby-builds:
    jobs:
      - build:
          matrix:
            parameters:
              ruby: ["2.4.1"]
              rails: ["4.2.11.1", "5.1.6.2", "5.1.7"]
              postgres: ["0.21.0"]
